/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Hammer from "./game/Hammer"
import GameManager from "./game/GameManager"
import Mouse from "./game/Mouse"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("game/Hammer.js",Hammer);
		reg("game/GameManager.js",GameManager);
		reg("game/Mouse.js",Mouse);
    }
}
GameConfig.width = 960;
GameConfig.height = 640;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "GameScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
