/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import game_m from "./game/game_m"
import hammer from "./game/hammer"
import mouse from "./game/mouse"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=960;
    static height:number=640;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="gameMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("game/game_m.ts",game_m);
        reg("game/hammer.ts",hammer);
        reg("game/mouse.ts",mouse);
    }
}
GameConfig.init();